# .github/workflows/build.yml
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: cargo build --release
      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/bandwidth-monitor
          tag: ${{ github.sha }}
          overwrite: true
          body: "Release of commit ${{ github.sha }}"